@baseUrl = http://localhost:3000

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "my_name",
  "email": "email@example.com",
  "password": "mypass123",
  "random": "random"
}




### Read All User
# @name readAllUser
GET {{baseUrl}}/user

### Read One User
# @name readOneUser
GET {{baseUrl}}/user/b50787b8-2fad-4b36-a4d3-27df978c43f8

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Brenno Levy",
  "email": "brennolevy@email.com",
  "password": "123456"
}
