@baseUrl = http://localhost:3000
@token = {{authLogin.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}
@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}

@userNameForTesting = Levy
@userEmailForTesting = levy@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = mypass123

# [AUTH] ===================================================================================

# POST

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "levy@email.com",
  "password": "123456"
}

# [USER] ===================================================================================


# GET

### Read All User
# @name readAllUser
GET {{baseUrl}}/user

### Read One User
# @name readOneUserById
GET {{baseUrl}}/user/98da17c4-abd2-4f4f-ac12-e57e4b7b2896
Authorization: Bearer {{token}}

### Read Logged In User
# @name readLoggedInUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}

# FIM GET

# POST

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "brenno",
  "email": "brenno@email.com",
  "password": "123456"
}

# FIM POST

# PATCH

### Update User
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"levy@email.com"
}

### Update Password
# @name updatePassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "123456",
  "newPassword": "mypass123"
}

# FIM PATCH

# DELETE

### Delete My Account
# @name deleteMyAccount
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{token}}

# FIM DELETE

# [POST] ===================================================================================

# GET

### Read all post public
# @name readAllPostPublic
GET {{baseUrl}}/post/

### Read one post public
# @name readOnePostPublic
GET {{baseUrl}}/post/{{postSlug}}

### Read all post owned
# @name readAllPostOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{token}}

### Read one post owned
# @name readOnePostOwned
GET {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{token}}

# FIM GET

# POST

### Create post owned
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Título de teste 6",
  "excerpt": "Criando post para teste 6",
  "content": "Testando update de post (antes do update)"
}

# FIM POST

# PATCH

### Update one post owned
# @name updateOnePostOwned
PATCH {{baseUrl}}/post/me/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "NOVO - Título do post",
  "excerpt": "NOVO - Excerto",
  "content": "NOVO - Conteúdo",
  "published": true
}

# FIM PATCH

# DELETE

### Delete one post owned
# @name deleteOnePostOwned
DELETE {{baseUrl}}/post/me/{{postUuid}}
Authorization: Bearer {{token}}

# FIM DELETE

# [UPLOAD] ===================================================================================

# GET

### Read Image
# @name readImage
GET {{imageUrl}}

# FIM GET

# POST

### Upload Image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="exemplo.png"
Content-Type: image/png

< ../dev/images/sample-image.jpeg
------BryenFormBoundary--

# FIM POST

# ================================================================================================
