@baseUrl = http://localhost:3000

@token = {{authLogin.response.body.accessToken}}

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "levygarcia@email.com",
  "password": "123456"
}

### Read All User
# @name readAllUser
GET {{baseUrl}}/user

### Read One User
# @name readOneUserById
GET {{baseUrl}}/user/80add8ed-8704-4ccb-90a7-5d268b6beff8
Authorization: Bearer {{token}}


### Find By Email
# @name findByEmail
GET {{baseUrl}}/user?user=brennolevy@email.com

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "levy",
  "email": "levy@email.com",
  "password": "123456"
}

### Update User
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"levy@email.com"
}
